# Generated by Django 5.2.7 on 2025-10-02 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardGames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, unique=True, verbose_name='Название игры')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Цена')),
                ('description', models.TextField(verbose_name='Описание игры')),
                ('players_number', models.CharField(max_length=6, verbose_name='Количество игроков')),
                ('game_time', models.CharField(max_length=30, verbose_name='Среднее время игры')),
                ('min_age', models.IntegerField(verbose_name='Минимальный возраст')),
            ],
            options={
                'verbose_name': 'Настольная игра',
                'verbose_name_plural': 'Настольные игры',
            },
        ),
        migrations.CreateModel(
            name='BonusCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(verbose_name='Баланс')),
                ('percentage_of_return', models.CharField(max_length=3, verbose_name='Процент возврата')),
                ('amount_of_purchases', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='Сумма покупок')),
            ],
            options={
                'verbose_name': 'Бонусная карта',
                'verbose_name_plural': 'Бонусные карты',
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, unique=True, verbose_name='Название жанра')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Количество')),
                ('board_game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board_app.boardgames', verbose_name='Настольная игра')),
            ],
        ),
        migrations.AddField(
            model_name='boardgames',
            name='games_categories',
            field=models.ManyToManyField(to='board_app.categories'),
        ),
        migrations.AddField(
            model_name='boardgames',
            name='games_genres',
            field=models.ManyToManyField(to='board_app.genres'),
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Количество')),
                ('board_game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board_app.boardgames', verbose_name='Настольная игра')),
            ],
        ),
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40, verbose_name='Имя')),
                ('surname', models.CharField(max_length=40, verbose_name='Фамилия')),
                ('middle_name', models.CharField(max_length=40, null=True, verbose_name='Отчество')),
                ('email', models.EmailField(max_length=50, null=True, verbose_name='Электронная почта')),
                ('phone_number', models.CharField(max_length=50, null=True, verbose_name='Телефон')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('bonus_card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board_app.bonuscards', verbose_name='Бонусная карта')),
                ('cart_items', models.ManyToManyField(related_name='in_cart', through='board_app.Cart', through_fields=('profile_id', 'board_game_id'), to='board_app.boardgames')),
                ('order', models.ManyToManyField(through='board_app.Orders', through_fields=('profile_id', 'board_game_id'), to='board_app.boardgames')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.AddField(
            model_name='orders',
            name='profile_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board_app.profiles', verbose_name='Профиль'),
        ),
        migrations.AddField(
            model_name='cart',
            name='profile_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board_app.profiles', verbose_name='Профиль'),
        ),
        migrations.CreateModel(
            name='Purchased',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Количество')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='Сумма')),
                ('bonus_amount', models.IntegerField(verbose_name='Количество бонусов')),
                ('board_game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board_app.boardgames', verbose_name='Настольная игра')),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board_app.profiles', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Покупка',
                'verbose_name_plural': 'Покупки',
            },
        ),
    ]
