# Generated by Django 5.2.7 on 2025-10-29 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0004_alter_boardgames_game_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgames',
            name='game_image',
            field=models.ImageField(upload_to='static/media/', verbose_name='Картинка игры'),
        ),
    ]
