# Generated by Django 5.2.8 on 2025-11-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0006_alter_boardgames_game_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgames',
            name='add_date',
            field=models.DateField(default='2025-01-01', verbose_name='Дата добавления'),
        ),
        migrations.AddField(
            model_name='boardgames',
            name='utm_source',
            field=models.IntegerField(default=0, verbose_name='Популярность'),
        ),
    ]
