# Generated by Django 5.2.8 on 2025-11-16 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0007_boardgames_add_date_boardgames_utm_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boardgames',
            old_name='utm_source',
            new_name='popularity',
        ),
    ]
