# Generated by Django 5.2.8 on 2025-11-30 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0008_rename_utm_source_boardgames_popularity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='bonus_card_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board_app.bonuscards', unique=True, verbose_name='Бонусная карта'),
        ),
    ]
